#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

registration:
    resource:
        path: '../src/Registration/Presentation/Controller/'
        namespace: App\Registration\Presentation\Controller
    type: attribute
